name: lack_off_debug_logs
description: A Flutter package for implementing a custom logging tool that captures global exceptions and network requests.
version: 0.0.5
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  sqflite: 2.2.8
  path: 1.8.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
