name: lack_off_debug_logs
description: A Flutter package for implementing a custom logging tool that captures global exceptions and network requests.
version: 0.0.9
homepage:

environment:
  #停留在这个版本主要是为了兼容鸿蒙
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=3.0.0"

dependencies:

  # 网络请求
  dio: 4.0.6
  path: 1.8.2
  sqflite: 2.2.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
repository: https://github.com/aniu7532/lack_off_bebug_logs
